name: Deploy Supabase Edge Function
on:
  push:
    branches: [main]
    paths:
      - 'supabase/functions/project1/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Supabase CLI
        run: |
          curl -L https://github.com/supabase/cli/releases/latest/download/supabase_ubuntu_amd64.deb -o supabase.deb
          sudo dpkg -i supabase.deb
          rm supabase.deb
      - name: Deploy Edge Function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: mlpgrevfohpiaepnnsch
        run: supabase functions deploy project1 --project-ref $SUPABASE_PROJECT_REF