name: Deploy Supabase Edge Functions
run-name: Deploying Supabase Edge Functions 🚀

on: [push]

jobs:
  Deploy-Edge-Functions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
    
    - name: Install Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
    
    - name: Verify Supabase Installation
      run: |
        supabase --version
    
    - name: List repository contents
      run: ls -la ${{ github.workspace }}
    
    - name: Deploy Supabase Edge Functions
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      run: |
        supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --debug
    
    - name: Job Status
      run: echo "Deployment status is ${{ job.status }}"
