name: Deploy Supabase Edge Functions
run-name: Deploying Supabase Edge Functions 🚀

on: [push]

jobs:
  Deploy-Edge-Functions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
    
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    
    - name: Install Supabase CLI
      run: |
        curl -sL https://supabase.com/docs/guides/cli/getting-started | bash
        echo "$HOME/.supabase/bin" >> $GITHUB_PATH
    
    - name: Verify Supabase and Deno Installation
      run: |
        deno --version
        supabase --version
    
    - name: List repository contents
      run: ls ${{ github.workspace }}
    
    - name: Deploy Supabase Edge Functions
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      run: |
        supabase functions deploy
    
    - name: Job Status
      run: echo "Deployment status is ${{ job.status }}"
